[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap_router = "8EqQZDrpuXAtWLpbv6q8PfCLF7hAJqvAKfgLs3Yoihy2"
vault = "AtomXVault1111111111111111111111111111111"

[programs.devnet]
swap_router = "8EqQZDrpuXAtWLpbv6q8PfCLF7hAJqvAKfgLs3Yoihy2"
vault = "AtomXVault1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
