[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap_router = "AgcU7r6U5uPEfFccmhYdMLcjckADdfoJ8QcHCgkG74Zg"
vault = "2ea7vwH3ziuFKC2DBwp81MjQpkTTbf4nhNefedcKREDy"

[programs.devnet]
swap_router = "AgcU7r6U5uPEfFccmhYdMLcjckADdfoJ8QcHCgkG74Zg"
vault = "2ea7vwH3ziuFKC2DBwp81MjQpkTTbf4nhNefedcKREDy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
